dist: trusty
language: java
jdk:
      - oraclejdk8
after_success:
      - mvn clean test jacoco:report coveralls:report
addons:
  sonarcloud:
    organization: "pnavais-github"   
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
